### ISSUE TITLE
Linux top command error

### ISSUE THREAD

**Issue by LuckyChen666** [LeeEirc/tclientlib#4]
When exec top commands,the contents add up and not refresh.

**Comment by LeeEirc** [comment]
how do you use this lib? try _example [telnet client](https://github.com/LeeEirc/tclientlib/tree/master/_example/telnet_client), show some snapshots.

**Comment by LuckyChen666** [comment]
![lALPDhmOuX4AqWDNAdjNAvE_753_472](https://user-images.githubusercontent.com/46469131/104993963-a7964180-5a5e-11eb-8605-33100be2cf8e.png)
you can see the picture,the first top data and the second top data show at the same time and not refresh in web terminal.

this is my  main code:
conf := tclientlib.Config{
		Username: username,
		Password: password,
		Timeout:  30 * time.Second,
		TTYOptions: &tclientlib.TerminalOptions{
			Wide: 122,
			High: 80,
		},
	}
con, err := tclientlib.Dial("tcp", ip, &conf)
	if err != nil {
		log.Println(err)
		os.Exit(1)
	}
buf := make([]byte, 1024)
	go func() {
		for {
			n, err := rw.Read(buf)  //rw is websocket conn
			if err != nil {
				errhandle(err.Error())
				break
			}
			if buf[0] == 13 {
				data := []byte{telnet.CR, telnet.LF}
				fmt.Println(data)
				_, err = con.Write(data)
				if err != nil {
					errhandle(err.Error())
					break
				}
			} else {
				_, err = con.Write(buf[:n])
				if err != nil {
					 errhandle(err.Error())
					break
				}
			}
		}
	}()
	for {
		buf := make([]byte, 1024)
		n, err := con.Read(buf)
		if err != nil {
			 errhandle(err.Error())
			break
		}
		_, err = rw.Write(buf[:n])
		if err != nil {
			errhandle(err.Error())
			continue
		}
	}

**Comment by LeeEirc** [comment]
I think it may your front-end code problem.
